#!/bin/bash
lightgreen='\e[1;32m'
lightred='\e[1;31m'
red='\e[0;31m'
lightyellow='\e[1;33m'
NC='\e[0m'
bold=`tput bold`
normal=`tput sgr0`
info(){
    echo -e "${lightgreen}info:${NC} ${bold}$1${normal}"
}
error(){
    echo -e "${lightred}error:${NC} ${bold}$1${normal}"
    exit 1
}
warn(){
    echo -e "${lightyellow}warn:${NC} ${bold}$1${normal}"
}
RELEASE=release

server_parameters(){
    while [[ "$#" -gt "0" ]]; do
        case $1 in
        "-d" | "-dir")
            DIR="${2}"
            shift
            ;;
        "-r")
            RUN_FLAG='1'
            RUN="${2}"
            shift
            ;;
        "-release")
            RELEASE="${2}"
            shift
            ;;
        *)
            error "$0: unknown option $1"
            ;;
        esac
        shift
    done
}

main(){
    server_parameters "$@"
    echo "#!/usr/bin/env bash" > "releases/$RELEASE.sh"
    for file in $(cat "src/$DIR/main.sh" | grep -Eo "(deps):[-A-Za-z0-9+&@#/%?=~_|\!:,.;]+" | sed 's/deps://g');do
        cat "src/$file" >> "releases/$RELEASE.sh"
        echo "" >> "releases/$RELEASE.sh"
    done
    cat "src/$DIR/main.sh" >> "releases/$RELEASE.sh"
    sed -i 's/#!\/bin\/bash//g' "releases/$RELEASE.sh"
    sed -i 's/#!\/usr\/bin\/env bash/#!\/bin\/bash/g' "releases/$RELEASE.sh"
    sed -i '/^$/d' "releases/$RELEASE.sh"
    sed -i "s/#name#/$RELEASE/g" "releases/$RELEASE.sh"
    [[ "$RUN_FLAG" -eq '1'  ]] && chmod +x "releases/$RELEASE.sh" && "releases/$RELEASE.sh" $RUN
}

main "$@"
